name: Android Pull Request & Master Unit Instrumented Test CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - '!master'

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [15, 29]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedAndroidTest --stacktrace